private_subnet_selector_key: ${private_subnet_selector_key}
private_subnet_selector_value: "${private_subnet_selector_value}"
security_group_selector_key: ${security_group_selector_key}
security_group_selector_value: "${security_group_selector_value}"
karpenter_ec2_capacity_type: "${instance_capacity_type}"
karpenter_ec2_instance_family: "${ec2_instance_family}"
karpenter_ec2_instance_type: "${ec2_instance_type}"
excluded_karpenter_ec2_instance_type: "${excluded_instance_type}"
provisioner_name: "${provisioner_name}"
instance_capacity_type: "${instance_capacity_type}"
kms_key_id: "${kms_key_id}"
ec2_node_name: "${ec2_node_name}"



spec:
  labels:
    ${karpenter_label}: "true"
    eks.amazonaws.com/nodegroup: "Services-ng"
